version: '3.8'
services:
  app:
    image: shahabuddinkhann/shopping-cart:latest
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:mysql://mysql:3306/shopping_cart
      - DB_USERNAME=app_user
      - DB_PASSWORD=app_password
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: shopping_cart
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: